Add support for options
aksyonov/mongoose-class-wrapper pull request #11
Opened 2017-04-29 17:08 UTC by mnsn

add support to ignore_getters_and_setter options so ecma6 that have
virtual properties that located in the schema will work
for instance if you have class
```javascript
class User{
get name (){
return this._namel
}
set name(value){
this._name=valuel
}
}
const UserSchema = new Schema ({
name:String
});
UserSchema.plugin(loadClass,User);
```
will throw an exception , let's let the user to decide if s/he wants to add virtual prorties or not

2017-04-29 19:37 UTC, aksyonov requested changes

2017-04-29 19:37 UTC, aksyonov commented on index.d.ts
> +declare function loadClass(schema: any, {target: any,options: object}:object): void;
Will this work when developer uses it without options, like `loadClass(schema, UserModel);`?

2017-04-29 19:37 UTC, aksyonov commented on README.md
> +	ignore_getters_and_setters:true
Please name options in camelCase, also use let or const for declaring options here.

2017-04-29 19:37 UTC, aksyonov commented on src/index.js
> +  let {options={},target=params} = params;
Please make your code consistent with existing code (add space after `,` and `:`, around `=`).

2017-05-01 17:02 UTC, mnsn commented on index.d.ts
> +declare function loadClass(schema: any, {target: any,options: object}:object): void;
Yes I kept on backward compatibility

2017-05-01 17:08 UTC, mnsn commented
Fixed the request changes

2017-05-01 20:38 UTC, aksyonov approved these changes

2017-05-01 20:39 UTC, merged